[lint]
# 1. Enable flake8-bugbear (`B`) rules, in addition to the defaults.
select = ["E4", "E7", "E9", "F", "B"]

# 2. Avoid enforcing line-length violations (`E501`)
ignore = ["E501"]

# 3. Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]

# 4. Ignore `E402` (import violations) in all `__init__.py` files, and in selected subdirectories.
[lint.per-file-ignores]
"demo/settings/__init__.py" = ["F403"]
"demo/settings/local.py" = ["F403"]
"demo/settings/prod.py" = ["F403"]
"demo/settings/stage.py" = ["F403"]
"*/api/__init__.py" = ["F401"]


[format]
# 5. Use single quotes in `ruff format`.
quote-style = "double"